// frontendVue/src/components/shared/GameOverlay.vue
<template>
  <div class="game-panel game-overlay-panel">
    <div class="game-info">
      <div class="game-title-container">
        <h2>{{ currentGame.name }}</h2>
        <span class="edit-pencil" @click="enableGameNameEdit" title="Editar nombre del juego">
          ✏️
        </span>
      </div>
      <div class="game-details">
        <div>
          Estado: <span>{{ getStatusText(currentGame.status) }}</span>
        </div>
        <div>
          Jugadores: <span>{{ currentGame.activeConnections || 0 }}</span>
        </div>
        <div>
          Propietario: <span>{{ currentUser.name }}</span>
        </div>
        <div>
          Usuario: <span>{{ currentUser.name }}</span>
        </div>
      </div>
    </div>
    
    <div class="game-details">
      GPS: <span>{{ gpsStatus }}</span>
    </div>
  </div>
</template>

<script setup lang="ts">
import { User, Game } from '../../types/index.js'
import { useToast } from '../../composables/useToast.js'

const { addToast } = useToast()

defineProps<{
  currentUser: User
  currentGame: Game
  gpsStatus: string
}>()

const getStatusText = (status: string) => {
  const statusMap: Record<string, string> = {
    stopped: 'Detenido',
    running: 'En Ejecución',
    paused: 'Pausado',
    finished: 'Finalizado'
  }
  return statusMap[status] || status
}

const enableGameNameEdit = () => {
  addToast({ message: 'Funcionalidad de edición de nombre en desarrollo', type: 'info' })
}
</script>

<style scoped>
.time-select-container {
  margin-top: 10px;
}
</style>

// frontend/src/components/GameOverlay.tsx
import React from 'react'
import { User, Game } from '../types'

interface GameOverlayProps {
  currentUser: User
  currentGame: Game
  isOwner: boolean
  goBack: () => void
}

const GameOverlay: React.FC<GameOverlayProps> = ({
  currentUser,
  currentGame,
  isOwner,
  goBack
}) => {
  return (
    <div className="game-overlay">
      <div className="game-header">
        <div className="game-title-section">
          <h1 className="game-title" id="gameTitle">
            {currentGame.name}
          </h1>
          {isOwner && (
            <span 
              className="edit-pencil" 
              id="editPencil"
              title="Editar nombre del juego"
            >
              ✏️
            </span>
          )}
        </div>
        
        <div className="game-info">
          <div className="game-status">
            <span className="status-label">Estado:</span>
            <span className="status-value" id="gameStatus">
              {currentGame.status}
            </span>
          </div>
          
          <div className="game-owner">
            <span className="owner-label">Propietario:</span>
            <span className="owner-value" id="gameOwner">
              {currentGame.owner.name}
            </span>
          </div>
          
          <div className="current-user">
            <span className="user-label">Tú:</span>
            <span className="user-value" id="currentUser">
              {currentUser.name}
            </span>
          </div>
        </div>
        
        <button className="btn btn-secondary back-btn" onClick={goBack}>
          ← Volver
        </button>
      </div>
    </div>
  )
}

export default GameOverlay
