// frontendSolidJS/src/components/GameOwner.tsx
import { createSignal, Show } from 'solid-js'
import { useToast } from '../contexts/ToastContext'
import { useGameOwner } from '../hooks/useGameOwner'
import '../styles/game-owner.css'

interface GameOwnerProps {
  gameId: string
}

export default function GameOwner(props: GameOwnerProps) {
  const { addToast: originalAddToast } = useToast()
  const [isTeamsDialogOpen, setIsTeamsDialogOpen] = createSignal(false)
  
  // Create a wrapper that matches the expected type
  const addToast = (toast: { message: string; type?: string }) => {
    originalAddToast({
      message: toast.message,
      type: toast.type as any
    })
  }

  const handleOpenTeamsDialog = () => {
    setIsTeamsDialogOpen(true)
  }

  const handleCloseTeamsDialog = () => {
    setIsTeamsDialogOpen(false)
  }
  
  const {
    currentUser,
    currentGame,
    isLoading,
    mapRef,
    mapInstanceRef,
    userMarkerRef,
    playerMarkersRef,
    controlPointMarkersRef,
    socket,
    startGame,
    pauseGame,
    resumeGame,
    endGame,
    restartGame,
    addTime,
    updateGameTime,
    goBack,
    reloadPage,
    centerOnUser,
    centerOnSite,
    openTeamsDialog,
    enableGameNameEdit,
    handleMapClick,
    controlPointMarkers,
    positionCircles,
    pieCharts,
    updateTeamCount,
    playerMarkers,
    isGameResultsDialogOpen,
    openGameResultsDialog,
    closeGameResultsDialog
  } = useGameOwner(props.gameId, addToast)

  const handleTeamCountChange = (count: number) => {
    updateTeamCount(count)
  }

  if (isLoading()) {
    return (
      <div class="loading">
        Cargando juego...
      </div>
    )
  }

  if (!currentGame() || !currentUser()) {
    return (
      <div class="loading">
        Error al cargar el juego
      </div>
    )
  }

  return (
    <div class="game-owner-container">
      {/* Map - To be implemented */}
      <div ref={mapRef} class="map-container" />
      
      {/* GPS Manager - To be implemented */}
      <div>
        {/* Player Marker - To be implemented */}
        <div />
        
        {/* Timer Manager - To be implemented */}
        <div>
          {/* Game Overlay - To be implemented */}
          <div class="game-overlay">
            <h3>{currentGame()?.name}</h3>
            <p>Estado: {currentGame()?.status}</p>
            <p>Jugadores: {currentGame()?.activeConnections}</p>
          </div>

          {/* Location Info - To be implemented */}
          <div class="location-info">
            <p>Información de ubicación</p>
          </div>
        </div>

        {/* Map Controls - To be implemented */}
        <div class="map-controls">
          <button onClick={goBack}>Volver</button>
          <button onClick={reloadPage}>Recargar</button>
          <button onClick={centerOnUser}>Centrar en mí</button>
          <button onClick={centerOnSite}>Centrar en sitio</button>
          <button onClick={handleOpenTeamsDialog}>Equipos</button>
          <button onClick={openGameResultsDialog}>Resultados</button>
        </div>
      </div>

      {/* Control Panel - To be implemented */}
      <div class="control-panel">
        <button onClick={startGame}>Iniciar</button>
        <button onClick={pauseGame}>Pausar</button>
        <button onClick={resumeGame}>Reanudar</button>
        <button onClick={endGame}>Finalizar</button>
        <button onClick={restartGame}>Reiniciar</button>
        <button onClick={() => addTime(300)}>+5 min</button>
      </div>

      {/* Players Dialog - To be implemented */}
      <Show when={isTeamsDialogOpen()}>
        <div class="players-dialog">
          <h3>Gestión de Equipos</h3>
          <p>Diálogo de equipos en desarrollo</p>
          <button onClick={handleCloseTeamsDialog}>Cerrar</button>
        </div>
      </Show>

      {/* Game Results Dialog - To be implemented */}
      <Show when={isGameResultsDialogOpen()}>
        <div class="game-results-dialog">
          <h3>Resultados del Juego</h3>
          <p>Diálogo de resultados en desarrollo</p>
          <button onClick={closeGameResultsDialog}>Cerrar</button>
        </div>
      </Show>
    </div>
  )
}

// frontend/src/components/GameOwner.tsx
import React, { useCallback, useState } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { useToast } from '../contexts/ToastContext'
import GameOwnerMap from './GameOwner/GameOwnerMap'
import GameOverlay from './GameOwner/GameOverlay'
import LocationInfo from './GameOwner/LocationInfo'
import ControlPanel from './GameOwner/ControlPanel'
import MapControls from './GameOwner/MapControls'
import PlayersDialog from './GameOwner/PlayersDialog'
import GameResultsDialog from './GameResultsDialog'
import { useGameOwner } from '../hooks/useGameOwner'
import { TimerManager } from './TimerManager'
import { GPSManager } from './GPSManager'
import '../styles/game-owner.css'

const GameOwner: React.FC = () => {
  const { gameId } = useParams<{ gameId: string }>()
  const navigate = useNavigate()
  const { addToast: originalAddToast } = useToast()
  const [isTeamsDialogOpen, setIsTeamsDialogOpen] = useState(false)
  
  // Create a wrapper that matches the expected type
  const addToast = useCallback((toast: { message: string; type?: string }) => {
    originalAddToast({
      message: toast.message,
      type: toast.type as any
    })
  }, [originalAddToast])

  const handleOpenTeamsDialog = useCallback(() => {
    setIsTeamsDialogOpen(true)
  }, [])

  const handleCloseTeamsDialog = useCallback(() => {
    setIsTeamsDialogOpen(false)
  }, [])
  
  const {
    currentUser,
    currentGame,
    isLoading,
    mapRef,
    mapInstanceRef,
    userMarkerRef,
    playerMarkersRef,
    controlPointMarkersRef,
    socket,
    startGame,
    pauseGame,
    resumeGame,
    endGame,
    restartGame,
    addTime,
    updateGameTime,
    goBack,
    reloadPage,
    centerOnUser,
    centerOnSite,
    openTeamsDialog,
    enableGameNameEdit,
    handleMapClick,
    controlPointMarkers,
    positionCircles,
    pieCharts,
    updateTeamCount,
    playerMarkers,
    isGameResultsDialogOpen,
    openGameResultsDialog,
    closeGameResultsDialog
  } = useGameOwner(gameId, navigate, addToast)

  const handleTeamCountChange = useCallback((count: number) => {
    updateTeamCount(count)
  }, [updateTeamCount])

  if (isLoading) {
    return (
      <div className="loading">
        Cargando juego...
      </div>
    )
  }

  if (!currentGame || !currentUser) {
    return (
      <div className="loading">
        Error al cargar el juego
      </div>
    )
  }

  return (
    <div className="game-owner-container">
      {/* Map */}
      <GameOwnerMap
        mapRef={mapRef}
        currentGame={currentGame}
        currentUser={currentUser}
        mapInstanceRef={mapInstanceRef}
        userMarkerRef={userMarkerRef}
        playerMarkersRef={playerMarkersRef}
        controlPointMarkersRef={controlPointMarkersRef}
        handleMapClick={handleMapClick}
        controlPointMarkers={controlPointMarkers}
        positionCircles={positionCircles}
        pieCharts={pieCharts}
        playerMarkers={playerMarkers}
      />

      {/* Timer Manager - Handles all timer functionality independently */}
      <TimerManager currentGame={currentGame} socket={socket}>
        {/* GPS Manager - Handles GPS tracking independently */}
        <GPSManager currentGame={currentGame} socket={socket}>
          {/* Game Overlay */}
          <GameOverlay
            currentGame={currentGame}
            currentUser={currentUser}
            enableGameNameEdit={enableGameNameEdit}
            socket={socket}
          />

          {/* Location Info */}
          <LocationInfo
            currentGame={currentGame}
            updateGameTime={async (timeInSeconds: number) => {
              await updateGameTime(timeInSeconds)
            }}
            openTeamsDialog={openTeamsDialog}
          />
        </GPSManager>
      </TimerManager>

      {/* Control Panel */}
      <ControlPanel
        currentGame={currentGame}
        startGame={async () => {
          await startGame()
        }}
        pauseGame={async () => {
          await pauseGame()
        }}
        resumeGame={async () => {
          await resumeGame()
        }}
        endGame={async () => {
          await endGame()
        }}
        restartGame={async () => {
          await restartGame()
        }}
      />

      {/* Map Controls */}
      <MapControls
        goBack={goBack}
        reloadPage={reloadPage}
        centerOnUser={centerOnUser}
        centerOnSite={centerOnSite}
        openTeamsDialog={handleOpenTeamsDialog}
        openResultsDialog={openGameResultsDialog}
      />

      {/* Players Dialog */}
      <PlayersDialog
        isOpen={isTeamsDialogOpen}
        onClose={handleCloseTeamsDialog}
        players={currentGame.players}
        currentGameId={currentGame.id}
        socket={socket}
        teamCount={currentGame.teamCount}
        onTeamCountChange={handleTeamCountChange}
      />
      {/* Game Results Dialog */}
      <GameResultsDialog
        isOpen={isGameResultsDialogOpen}
        onClose={closeGameResultsDialog}
        currentGame={currentGame}
        gameId={gameId}
      />
    </div>
  )
}

export default GameOwner
