// frontend/src/components/Login.vue
<template>
  <div class="login-container">
    <div class="card login-card">
      <h1 class="login-title">Iniciar Sesión</h1>
      <form id="loginForm" class="login-form" @submit.prevent="handleSubmit">
        <div class="form-group">
          <label for="email" class="form-label">Email:</label>
          <input
            type="email"
            id="email"
            name="email"
            class="form-input"
            required
            v-model="email"
          />
        </div>
        
        <div class="form-group">
          <label for="password" class="form-label">Contraseña:</label>
          <input
            type="password"
            id="password"
            name="password"
            class="form-input"
            required
            v-model="password"
          />
        </div>
        
        <button type="submit" class="btn btn-primary" :disabled="loading">
          {{ loading ? 'Cargando...' : 'Ingresar' }}
        </button>
      </form>
      
      <div class="login-links">
        <p>¿No tienes cuenta? <router-link to="/register">Regístrate aquí</router-link></p>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { AuthService } from '../services/auth.js'
import { useToast } from '../composables/useToast.js'

const router = useRouter()
const { addToast } = useToast()

const email = ref('')
const password = ref('')
const loading = ref(false)

const handleSubmit = async () => {
  loading.value = true

  try {
    const authResponse = await AuthService.login({ 
      email: email.value, 
      password: password.value 
    })
    
    addToast({ message: 'Login exitoso', type: 'success' })
    
    try {
      await router.push('/dashboard')
    } catch (navError) {
      console.error('Login: Error en navegación:', navError)
      // Si falla la navegación, intentar redirección forzada
      window.location.href = '/dashboard'
    }
    
  } catch (error) {
    console.error('Login: Error en login:', error)
    addToast({ message: 'Error en login: ' + (error as Error).message, type: 'error' })
  } finally {
    loading.value = false
  }
}
</script>

<style scoped>
.login-container {
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 100vh;
  background: var(--background);
  padding: 20px;
}

.login-card {
  width: 100%;
  max-width: 400px;
  padding: 2rem;
}

.login-title {
  text-align: center;
  margin-bottom: 2rem;
  color: var(--text-primary);
  font-size: 1.5rem;
  font-weight: 600;
}

.login-form {
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
}

.form-group {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.form-label {
  font-weight: 500;
  color: var(--text-primary);
  font-size: 0.9rem;
}

.form-input {
  padding: 0.75rem;
  border: 1px solid var(--border);
  border-radius: 4px;
  background: var(--card-background);
  color: var(--text-primary);
  font-size: 1rem;
  transition: border-color 0.2s ease;
}

.form-input:focus {
  outline: none;
  border-color: var(--primary);
}


.login-links {
  margin-top: 1.5rem;
  text-align: center;
  color: var(--text-muted);
  font-size: 0.9rem;
}

.login-links a {
  color: var(--primary);
  text-decoration: none;
}

.login-links a:hover {
  text-decoration: underline;
}
</style>

// frontend/src/components/Login.tsx
import React, { useState } from 'react'
import { useNavigate, Link } from 'react-router-dom'
import { AuthService } from '../services/auth.js'
import { useToast } from '../contexts/ToastContext.js'

interface LoginProps {
  onLogin: (user: any) => void
}

const Login: React.FC<LoginProps> = ({ onLogin }) => {
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [loading, setLoading] = useState(false)
  const navigate = useNavigate()
  const { addToast } = useToast()

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    setLoading(true)

    const submitLogin = async () => {
      try {
        const authResponse = await AuthService.login({ email, password })
        
        onLogin(authResponse.user)
        
        addToast({ message: 'Login exitoso', type: 'success' })
        
        try {
          navigate('/dashboard')
        } catch (navError) {
          console.error('Login: Error en navegación:', navError)
          // Si falla la navegación, intentar redirección forzada
          window.location.href = '/dashboard'
        }
        
      } catch (error) {
        console.error('Login: Error en login:', error)
        addToast({ message: 'Error en login: ' + (error as Error).message, type: 'error' })
      } finally {
        setLoading(false)
      }
    }

    submitLogin()
  }

  return (
    <div className="login-container">
      <div className="card login-card">
        <h1 className="login-title">Iniciar Sesión</h1>
        <form id="loginForm" className="login-form" onSubmit={handleSubmit}>
          <div className="form-group">
            <label htmlFor="email" className="form-label">Email:</label>
            <input
              type="email"
              id="email"
              name="email"
              className="form-input"
              required
              value={email}
              onChange={(e) => setEmail(e.target.value)}
            />
          </div>
          
          <div className="form-group">
            <label htmlFor="password" className="form-label">Contraseña:</label>
            <input
              type="password"
              id="password"
              name="password"
              className="form-input"
              required
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />
          </div>
          
          <button type="submit" className="btn btn-primary" disabled={loading}>
            {loading ? 'Cargando...' : 'Ingresar'}
          </button>
        </form>
        
        <div className="login-links">
          <p>¿No tienes cuenta? <Link to="/register">Regístrate aquí</Link></p>
        </div>
      </div>
    </div>
  )
}

export default Login
