// frontend/src/components/Register.vue
<template>
  <div class="register-container">
    <div class="card register-card">
      <h1 class="register-title">Crear Cuenta</h1>
      <form id="registerForm" class="register-form" @submit.prevent="handleSubmit">
        <div class="form-group">
          <label for="name" class="form-label">Nombre:</label>
          <input 
            type="text" 
            id="name" 
            name="name" 
            class="form-input" 
            required
            v-model="name"
          />
        </div>
        
        <div class="form-group">
          <label for="email" class="form-label">Email:</label>
          <input 
            type="email" 
            id="email" 
            name="email" 
            class="form-input" 
            required
            v-model="email"
          />
        </div>
        
        <div class="form-group">
          <label for="password" class="form-label">Contraseña:</label>
          <input 
            type="password" 
            id="password" 
            name="password" 
            class="form-input" 
            required 
            minlength="6"
            v-model="password"
          />
        </div>
        
        <div class="form-group">
          <label for="confirmPassword" class="form-label">Confirmar Contraseña:</label>
          <input 
            type="password" 
            id="confirmPassword" 
            name="confirmPassword" 
            class="form-input" 
            required
            v-model="confirmPassword"
          />
        </div>
        
        <button type="submit" class="btn btn-primary" :disabled="loading">
          {{ loading ? 'Cargando...' : 'Registrarse' }}
        </button>
      </form>
      
      <div class="register-links">
        <p>¿Ya tienes cuenta? <router-link to="/login">Inicia sesión aquí</router-link></p>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { AuthService } from '../services/auth.js'
import { useToast } from '../composables/useToast.js'

const router = useRouter()
const { addToast } = useToast()

const name = ref('')
const email = ref('')
const password = ref('')
const confirmPassword = ref('')
const loading = ref(false)

const handleSubmit = async () => {
  if (password.value !== confirmPassword.value) {
    addToast({ message: 'Las contraseñas no coinciden', type: 'error' })
    return
  }

  if (password.value.length < 6) {
    addToast({ message: 'La contraseña debe tener al menos 6 caracteres', type: 'error' })
    return
  }

  loading.value = true

  try {
    await AuthService.register({ 
      name: name.value, 
      email: email.value, 
      password: password.value 
    })
    addToast({ message: '¡Cuenta creada exitosamente! Redirigiendo...', type: 'success' })
    
    setTimeout(() => {
      router.push('/login')
    }, 2000)
  } catch (error) {
    addToast({ message: 'Error en registro: ' + (error as Error).message, type: 'error' })
  } finally {
    loading.value = false
  }
}
</script>

<style scoped>
.register-container {
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 100vh;
  background: var(--background);
  padding: 20px;
}

.register-card {
  width: 100%;
  max-width: 400px;
  padding: 2rem;
}

.register-title {
  text-align: center;
  margin-bottom: 2rem;
  color: var(--text-primary);
  font-size: 1.5rem;
  font-weight: 600;
}

.register-form {
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
}

.form-group {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.form-label {
  font-weight: 500;
  color: var(--text-primary);
  font-size: 0.9rem;
}

.form-input {
  padding: 0.75rem;
  border: 1px solid var(--border);
  border-radius: 4px;
  background: var(--card-background);
  color: var(--text-primary);
  font-size: 1rem;
  transition: border-color 0.2s ease;
}

.form-input:focus {
  outline: none;
  border-color: var(--primary);
}


.register-links {
  margin-top: 1.5rem;
  text-align: center;
  color: var(--text-muted);
  font-size: 0.9rem;
}

.register-links a {
  color: var(--primary);
  text-decoration: none;
}

.register-links a:hover {
  text-decoration: underline;
}
</style>

// frontend/src/components/Register.tsx
import React, { useState } from 'react'
import { useNavigate, Link } from 'react-router-dom'
import { AuthService } from '../services/auth.js'
import { useToast } from '../contexts/ToastContext.js'

const Register: React.FC = () => {
  const [name, setName] = useState('')
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [confirmPassword, setConfirmPassword] = useState('')
  const [loading, setLoading] = useState(false)
  const navigate = useNavigate()
  const { addToast } = useToast()

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    
    if (password !== confirmPassword) {
      addToast({ message: 'Las contraseñas no coinciden', type: 'error' })
      return
    }

    if (password.length < 6) {
      addToast({ message: 'La contraseña debe tener al menos 6 caracteres', type: 'error' })
      return
    }

    setLoading(true)

    try {
      await AuthService.register({ name, email, password })
      addToast({ message: '¡Cuenta creada exitosamente! Redirigiendo...', type: 'success' })
      
      setTimeout(() => {
        navigate('/login')
      }, 2000)
    } catch (error) {
      addToast({ message: 'Error en registro: ' + (error as Error).message, type: 'error' })
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="register-container">
      <div className="card register-card">
        <h1 className="register-title">Crear Cuenta</h1>
        <form id="registerForm" className="register-form" onSubmit={handleSubmit}>
          <div className="form-group">
            <label htmlFor="name" className="form-label">Nombre:</label>
            <input 
              type="text" 
              id="name" 
              name="name" 
              className="form-input" 
              required
              value={name}
              onChange={(e) => setName(e.target.value)}
            />
          </div>
          
          <div className="form-group">
            <label htmlFor="email" className="form-label">Email:</label>
            <input 
              type="email" 
              id="email" 
              name="email" 
              className="form-input" 
              required
              value={email}
              onChange={(e) => setEmail(e.target.value)}
            />
          </div>
          
          <div className="form-group">
            <label htmlFor="password" className="form-label">Contraseña:</label>
            <input 
              type="password" 
              id="password" 
              name="password" 
              className="form-input" 
              required 
              minLength={6}
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />
          </div>
          
          <div className="form-group">
            <label htmlFor="confirmPassword" className="form-label">Confirmar Contraseña:</label>
            <input 
              type="password" 
              id="confirmPassword" 
              name="confirmPassword" 
              className="form-input" 
              required
              value={confirmPassword}
              onChange={(e) => setConfirmPassword(e.target.value)}
            />
          </div>
          
          <button type="submit" className="btn btn-primary" disabled={loading}>
            {loading ? 'Cargando...' : 'Registrarse'}
          </button>
        </form>
        
        <div className="register-links">
          <p>¿Ya tienes cuenta? <Link to="/login">Inicia sesión aquí</Link></p>
        </div>
      </div>
    </div>
  )
}

export default Register
