// frontend/src/App.tsx
import { useState, useEffect } from 'react'
import { BrowserRouter as Router, Routes, Route, Navigate } from 'react-router-dom'
import { AuthService } from './services/auth.js'
import { User } from './types/index.js'
import Login from './components/Login.js'
import Register from './components/Register.js'
import Dashboard from './components/Dashboard.js'
import CreateGame from './components/CreateGame.js'
import GameOwner from './components/GameOwner.js'
import GamePlayer from './components/GamePlayer.js'
import { ToastProvider } from './contexts/ToastContext.js'

function App() {
  const [currentUser, setCurrentUser] = useState<User | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    const user = AuthService.getCurrentUser()
    setCurrentUser(user)
    setLoading(false)
  }, [])

  // Función para actualizar el usuario que se pasa a los componentes
  const handleLogin = (user: User) => {
    setCurrentUser(user)
  }

  if (loading) {
    return (
      <div className="loading">
        <div>Cargando Milsim...</div>
      </div>
    )
  }

  return (
    <ToastProvider>
      <Router>
        <Routes>
          <Route 
            path="/login"
            element={
              currentUser ? <Navigate to="/dashboard" replace /> : <Login onLogin={handleLogin} />
            }
          />
          <Route
            path="/register"
            element={
              currentUser ? <Navigate to="/dashboard" replace /> : <Register />
            }
          />
          <Route
            path="/dashboard"
            element={
              currentUser ? <Dashboard currentUser={currentUser} /> : <Navigate to="/login" replace />
            }
          />
          <Route 
            path="/create-game" 
            element={
              currentUser ? <CreateGame currentUser={currentUser} /> : <Navigate to="/login" replace />
            } 
          />
          <Route
            path="/owner/:gameId"
            element={
              currentUser ? <GameOwner /> : <Navigate to="/login" replace />
            }
          />
          <Route
            path="/player/:gameId"
            element={
              currentUser ? <GamePlayer /> : <Navigate to="/login" replace />
            }
          />
          <Route path="/" element={<Navigate to={currentUser ? "/dashboard" : "/login"} replace />} />
        </Routes>
      </Router>
    </ToastProvider>
  )
}

export default App

// frontendSolidJS/src/App.tsx
import { createSignal, onMount, Show } from 'solid-js'
import { Route, Navigate, useParams, Router } from '@solidjs/router'
import { AuthService } from './services/auth'
import { User } from './types/index'
import Login from './components/Login'
import Register from './components/Register'
import Dashboard from './components/Dashboard'
import CreateGame from './components/CreateGame'
import GameOwner from './components/GameOwner'
import GamePlayer from './components/GamePlayer'
import { ToastProvider } from './contexts/ToastContext'

// Componente wrapper para GameOwner que obtiene el gameId de los parámetros
function GameOwnerWrapper() {
  const params = useParams()
  return <GameOwner gameId={params.gameId ?? ''} />
}

// Componente wrapper para GamePlayer que obtiene el gameId de los parámetros
function GamePlayerWrapper() {
  const params = useParams()
  return <GamePlayer gameId={params.gameId ?? ''} />
}

function App() {
  const [currentUser, setCurrentUser] = createSignal<User | null>(null)
  const [loading, setLoading] = createSignal(true)

  onMount(() => {
    const user = AuthService.getCurrentUser()
    setCurrentUser(user)
    setLoading(false)
  })

  // Función para actualizar el usuario que se pasa a los componentes
  const handleLogin = (user: User) => {
    setCurrentUser(user)
  }

  return (
    <Show when={!loading()} fallback={
      <div class="loading">
        <div>Cargando Milsim...</div>
      </div>
    }>
      <Route path="/login" component={() =>
        currentUser() ? <Navigate href="/dashboard" /> : <Login onLogin={handleLogin} />
      } />
      
      <Route path="/register" component={() =>
        currentUser() ? <Navigate href="/dashboard" /> : <Register />
      } />
      
      <Route path="/dashboard" component={() =>
        currentUser() ? <Dashboard currentUser={currentUser()} /> : <Navigate href="/login" />
      } />
      
      <Route path="/create-game" component={() =>
        currentUser() ? <CreateGame currentUser={currentUser()} /> : <Navigate href="/login" />
      } />
      
      <Route path="/owner/:gameId" component={GameOwnerWrapper} />
      
      <Route path="/player/:gameId" component={GamePlayerWrapper} />
      
      <Route path="/" component={() =>
        <Navigate href={currentUser() ? "/dashboard" : "/login"} />
      } />
    </Show>
  )
}

function AppWrapper() {
  return (
    <ToastProvider>
      <Router>
        <App />
      </Router>
    </ToastProvider>
  )
}

export default AppWrapper
