// frontend/src/components/GamePlayer.tsx
import React, { useCallback, useState } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { useToast } from '../contexts/ToastContext'
import GamePlayerMap from './GamePlayer/GamePlayerMap'
import GameOverlay from './GamePlayer/GameOverlay'
import LocationInfo from './GamePlayer/LocationInfo'
import MapControls from './GamePlayer/MapControls'
import GameResultsDialog from './GameResultsDialog'
import TeamSelection from './TeamSelection'
import { useGamePlayer } from '../hooks/useGamePlayer'
import { TimerManager } from './TimerManager'
import { GPSManager } from './GPSManager'
import '../styles/game-player.css'

const GamePlayer: React.FC = () => {
  const { gameId } = useParams<{ gameId: string }>()
  const navigate = useNavigate()
  const { addToast: originalAddToast } = useToast()
  
  // Create a wrapper that matches the expected type
  const addToast = useCallback((toast: { message: string; type?: string }) => {
    originalAddToast({
      message: toast.message,
      type: toast.type as any
    })
  }, [originalAddToast])

  const {
    currentUser,
    currentGame,
    isLoading,
    mapRef,
    mapInstanceRef,
    userMarkerRef,
    playerMarkersRef,
    controlPointMarkersRef,
    socket,
    goBack,
    reloadPage,
    centerOnUser,
    centerOnSite,
    controlPointMarkers,
    positionCircles,
    pieCharts,
    isGameResultsDialogOpen,
    openGameResultsDialog,
    closeGameResultsDialog,
    showTeamSelection,
    hideTeamSelection,
    showTeamSelectionManual
  } = useGamePlayer(gameId, navigate, addToast)

  // Timer and GPS functionality is now handled by isolated managers

  if (isLoading) {
    return (
      <div className="loading">
        Cargando juego...
      </div>
    )
  }

  if (!currentGame || !currentUser) {
    return (
      <div className="loading">
        Error al cargar el juego
      </div>
    )
  }

  return (
    <div className="game-owner-container">
      {/* Map */}
      <GamePlayerMap
        mapRef={mapRef}
        currentGame={currentGame}
        currentUser={currentUser}
        mapInstanceRef={mapInstanceRef}
        userMarkerRef={userMarkerRef}
        playerMarkersRef={playerMarkersRef}
        controlPointMarkersRef={controlPointMarkersRef}
        controlPointMarkers={controlPointMarkers}
        positionCircles={positionCircles}
        pieCharts={pieCharts}
      />

      {/* GPS Manager - Handles GPS tracking independently */}
      <GPSManager currentGame={currentGame} socket={socket}>
        {/* Timer Manager - Handles all timer functionality independently */}
        <TimerManager currentGame={currentGame} socket={socket}>
          {/* Game Overlay */}
          <GameOverlay
            currentUser={currentUser}
            currentGame={currentGame}
            socket={socket}
          />
        </TimerManager>

        {/* Location Info */}
        <LocationInfo
          currentGame={currentGame}
        />
      </GPSManager>

      {/* Map Controls */}
      <MapControls
        goBack={goBack}
        reloadPage={reloadPage}
        centerOnUser={centerOnUser}
        centerOnSite={centerOnSite}
        openResultsDialog={openGameResultsDialog}
        showTeamSelection={showTeamSelectionManual}
        gameStatus={currentGame?.status}
      />
      {/* Game Results Dialog */}
      <GameResultsDialog
        isOpen={isGameResultsDialogOpen}
        onClose={closeGameResultsDialog}
        currentGame={currentGame}
        gameId={gameId}
      />

      {/* Team Selection */}
      {showTeamSelection && currentGame && currentUser && socket && (
        <TeamSelection
          currentGame={currentGame}
          currentUser={currentUser}
          socket={socket}
          onTeamSelected={hideTeamSelection}
        />
      )}
    </div>
  )
}

export default GamePlayer

// frontendSolidJS/src/components/GamePlayer.tsx
import { createSignal, Show } from 'solid-js'
import { useToast } from '../contexts/ToastContext'
import { useGamePlayer } from '../hooks/useGamePlayer'
import '../styles/game-player.css'

interface GamePlayerProps {
  gameId: string
}

export default function GamePlayer(props: GamePlayerProps) {
  const { addToast: originalAddToast } = useToast()
  
  // Create a wrapper that matches the expected type
  const addToast = (toast: { message: string; type?: string }) => {
    originalAddToast({
      message: toast.message,
      type: toast.type as any
    })
  }

  const {
    currentUser,
    currentGame,
    isLoading,
    mapRef,
    mapInstanceRef,
    userMarkerRef,
    playerMarkersRef,
    controlPointMarkersRef,
    socket,
    goBack,
    reloadPage,
    centerOnUser,
    centerOnSite,
    controlPointMarkers,
    positionCircles,
    pieCharts,
    isGameResultsDialogOpen,
    openGameResultsDialog,
    closeGameResultsDialog,
    showTeamSelection,
    hideTeamSelection,
    showTeamSelectionManual
  } = useGamePlayer(props?.gameId ?? '', addToast)

  if (isLoading()) {
    return (
      <div class="loading">
        Cargando juego...
      </div>
    )
  }

  if (!currentGame() || !currentUser()) {
    return (
      <div class="loading">
        Error al cargar el juego
      </div>
    )
  }

  return (
    <div class="game-player-container">
      {/* Map - To be implemented */}
      <div ref={mapRef} class="map-container" />
      
      {/* GPS Manager - To be implemented */}
      <div>
        {/* Player Marker - To be implemented */}
        <div />
        
        {/* Timer Manager - To be implemented */}
        <div>
          {/* Game Overlay - To be implemented */}
          <div class="game-overlay">
            <h3>{currentGame()?.name}</h3>
            <p>Estado: {currentGame()?.status}</p>
            <p>Jugadores: {currentGame()?.activeConnections}</p>
          </div>

          {/* Location Info - To be implemented */}
          <div class="location-info">
            <p>Información de ubicación</p>
          </div>
        </div>

        {/* Map Controls - To be implemented */}
        <div class="map-controls">
          <button onClick={goBack}>Volver</button>
          <button onClick={reloadPage}>Recargar</button>
          <button onClick={centerOnUser}>Centrar en mí</button>
          <button onClick={centerOnSite}>Centrar en sitio</button>
          <button onClick={showTeamSelectionManual}>Cambiar equipo</button>
          <button onClick={openGameResultsDialog}>Resultados</button>
        </div>
      </div>

      {/* Team Selection Dialog - To be implemented */}
      <Show when={showTeamSelection()}>
        <div class="team-selection-dialog">
          <h3>Seleccionar Equipo</h3>
          <p>Diálogo de selección de equipo en desarrollo</p>
          <button onClick={hideTeamSelection}>Cerrar</button>
        </div>
      </Show>

      {/* Game Results Dialog - To be implemented */}
      <Show when={isGameResultsDialogOpen()}>
        <div class="game-results-dialog">
          <h3>Resultados del Juego</h3>
          <p>Diálogo de resultados en desarrollo</p>
          <button onClick={closeGameResultsDialog}>Cerrar</button>
        </div>
      </Show>
    </div>
  )
}
